<div class="well">
<h2>Team Training</h2>

We offer individual in-house Trainings which are individually suited to your needs,
all our trainings have a strong focus on the practical usage aswell deliver theoretical backgrounds.
<br />
All Trainings are offered in English or German language.
There is also an option to hold some parts of the training in Dutch.
<br />
<h2>Education Providers</h2>
Education Providers are welcome to book us for Public Trainings<br />
        

</div>