<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('WebConsults.EU Training & Consulting')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->prependStylesheet($this->basePath() . '/css/SyntaxHighlighter/shCore.css')
                    ->prependStylesheet($this->basePath() . '/css/SyntaxHighlighter/shThemeDefault.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')            
                                  ->prependFile($this->basePath() . '/js/SyntaxHighlighter/shAutoloader.js')
                                  ->prependFile($this->basePath() . '/js/SyntaxHighlighter/shCore.js')
                                  ->appendFile($this->basePath() . '/js/SyntaxHighlighter/shBrushPhp.js')
                                  ->appendFile($this->basePath() . '/js/SyntaxHighlighter/shBrushJScript.js')
                                  ->appendScript("SyntaxHighlighter.all();", "text/javascript")
                                  ->appendScript("https://maps.googleapis.com/maps/api/js?sensor=false", "text/javascript")
                                  
    ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>" alt="<?php echo $this->translate('Webconsults EU Development and consulting') ?>" style="height:100%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
              <li ><a href="/training"><?php echo $this->translate('Training') ?></a></li>
              <li ><a href="/consulting"><?php echo $this->translate('Consulting') ?></a></li>
              <li ><a href="/development"><?php echo $this->translate('Development')?></a></li>
              <li ><a href="/blog"><?php echo $this->translate('Techblog') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


      
    <div class="container" style="margin-top: 40px;">
        <div class="row-fluid">
<div class="span2">
    <div class="well sidebar-nav">
	            <ul class="nav nav-list">
	              <li class="nav-header">WebConsults</li>
	              <li><a href="/">Home</a></li>
	              <li><a href="<?=$this->url('blog')?>">Techblog</a></li>
                      <li><a href="<?=$this->url('consulting')?>">Consulting</a></li>
                      <li><a href="<?=$this->url('development')?>">Development</a></li>
                      <li class="nav-header">Training</li>	              
	              <li><a href="<?=$this->url('training')?>">Training</a></li>
                      <li class="nav-header">Contact</li>	              
	              <li><a href="<?=$this->url('contact')?>">Office</a></li>
                      <li><a href="http://www.xing.com/profile/John_Behrens">Xing</a></li>                      
	            </ul>
    </div>
</div>
        <div class="span10">
        
        
      <?php echo $this->content; ?>
</div>
        </div>
      <hr>

      <footer>
        <p>&copy; 2008 - <?=date("Y")?> by WebConsults.eu <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
