
<?php $this->headTitle("Edit/Add Entry"); ?>
<div clas="well">
<h1><?php echo $title; ?></h1>
use &lt;pre class="brush: php"&gt; tags for code

    <?php $form = $this->form; ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($form->get('title')); ?>
<?php echo $this->formRow($form->get('text')); ?>
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->formInput($form->get('submitEntry')); ?> 
<?php echo $this->form()->closeTag($form); ?>
</div>