<div class="well">
<h2>John Behrens - WebDevelopment Consultant</h2>
<h3> Support for your Projects </h3>

John Berhrens works in Software Development since his schooltimes in the mid of the 90s. He has work experience in a lot of well known companies across Europe in all kind of branches like media and entertainment, consumer electronics, banking and finance. 
<br />
John Behrens has great experience in creating enterprise web applications focused on performance and security.



<h3>Occupation</h3>
         Fachinformatiker Anwendungsentwicklung (IT Specialist - Application Development) 2006<br />
         Certified Professional for Software Architecture - ISAQB <br />
2011
         Certified Scrum Master (CSM) - ScrumAlliance - 2011<br />
         Projektleiter IHK ( Projectleader) - Wirtschaftsakademie SH - 2012<br /> 
<h3>Skills</h3>

<h3>PHP </h3>
<ul>
    <li>PHP Version 5</li>
    <li>OOP</li>    
    <li>High Traffic</li>
    <li>High Security</li>
    <li>Zend Framework 1,2</li>
    <li>Symfony Framework 1,2</li>
    <li>PHP Unit</li>
</ul>

<h4>JavaScript</h4>
<ul>  
    <li>JQuery</li>
    <li>Prototype</li>
    <li>AJAX</li>
    <li>JSON</li>
</ul>
<h4>Web Standards</h4>
<ul>
   <li>xHTML</li>
   <li>CSS</li>
</ul>
<h4>Databases</h4>
  <ul>
      <li>Database Design</li>
      <li>Query Optimization</li>
      <li>Layout Optimization</li>
      <li>Performance Optimization</li>
      <li>MySql</li>
      <li>Oracle</li>
      <li>MsSql</li> 

  </ul>
<h4>Java</h4>
<ul>
  <li>Java Basics</li>
  <li>Swing</li>
  <li>JUnit</li>
</ul>
<h4>Testing and Quality Assurance</h4>
<ul>
   <li>Selenium</li>
   <li>JUnit</li>
   <li>PHP Unit</li>
</ul>

<h4>Protocols</h4>
<ul>
 <li>SOAP</li>
 <li>XML-RPC</li>
 <li>REST</li>
 <li>RSS</li>
 <li>OpenID</li>
 <li>OpenSocial</li>
 <li>Web Single Sign On Solutions</li>
</ul>
<h4>Other Technologies</h4>
 <ul>
   <li>Delphi
   <li>C / C++
   <li>Perl
   <li>Single Sign On, OAuth, OpenID
 </ul>
<h4>Languages</h4>
<ul>
    <li>German</li>
    <li>English</li>
    <li>Dutch</li>
</ul>

 <h4>Work Experience</h4>
 <ul>
     <li><a href="http://www.deutschepost.de">Deutsche Post AG</a> - Bonn - Germany</li>
     <li><a href="http://www.computerbild.de">Computerbild Online GmbH</a> - Hamburg - Germany</li>
     <li> <a href="http://www.unicredit.eu">HVB(Unicredit Group)</a> - Munich - Germany</li>
     <li><a href="http://www.tomtom.com">TomTom International B.V.</a> - Amsterdam - Netherlands</li>
     <li><a href="http://www.kemper-ko.nl">Kemper & Ko </a> - Amsterdam  - Netherlands</li>
     <li><a href="http://www.cellcast.tv">Cellcast TV</a> - London - United Kingdom</li>
     <li><a href="http://www.orangemedia.de">Orangemedia.de</a> GmbH - Hamburg - Germany</li>
     <li><a href="http://www.hbv.de">Heinrich Bauer Verlagsgruppe</a> - Hamburg - Germany</li>
 </ul>

<h4>Availability</h4>
John Behrens is is available for contract agreements all over Europe.
<br />
<img src="/templates/webconsults/img/contact.gif" alt="Webconsults John Behrens" />

</div>