<div class="well">
<h2>Für Unternehmen</h2>
Gerade in der IT ist die konsequente Weiterbildung auf dem Stand der neuesten Technologien ein Muss. Gerne unterstützen wir durch sorgfältig vorbereitere Lern-Workshops die Weiterbildung ihrer Mitarbeiter. Im Gegensatz zu größeren Schulungsanbietern können wir bei Inhouse-Schulungen direkt auf ihre Unternehmensbedürfnisse eingehen.
<br />
zu folgenden Themengebieten haben wir vorbereitete Trainings

<ul>
    <li>Zend Framework 2</li>
    <li>Test Driven Development mit PHP</li>
    <li>Software Craftmanship Skills</li>
    <li>MySQL Performance für Entwickler</li>
    <li>Objekt Orientierte Programmierung</li>
</ul>

<h2>Weiterbildungs Anbieter</h2>
Als Weiterbildungsanbieter können Sie uns gerne auch für offene Trainings buchen.        

</div>