
<div class="row">
    <h1>WebConsults.eu</h1>
<div class="span 1"></div>    
<div class="span6 well">
    
    <h1><?php echo sprintf($this->translate('WebConsults.eu'), '<span class="zf-green">', '</span>') ?></h1>
    Webentwicklung ist unser Themengebiet hierbei arbeiten wir jederzeit mit aktuellen Technologien und Methoden.
    Hierzu gehören unter anderem PHP, MySQL , Zend Framework 2, NoSQL, SOA, SCRUM, Agile, PHP Unit, Test Driven Development, Netbeans, Linux, NoSQL, JQuery.
    Technische Informationen, Updates und Tutorials gibt es auf unserem 
   <a href="<?=$this->url('blog')?>" target="_blank">Techblog</a> <br />
    <p><a class="btn btn-primary btn-large" href="<?=$this->url('blog')?>"><?php echo $this->translate('Techblog') ?> &raquo;</a></p>
</div>
    
<div class="span3 well">
<div class="span 1"></div>    
       <h2><?php echo $this->translate('Contact') ?></h2>
       <p>Unser Büro in Elmshorn bei Hamburg</p>       
       <p><a class="btn btn-primary" href="<?=$this->url('contact')?>"><?php echo $this->translate('Contact') ?> &raquo;</a></p>
       <a href="http://www.xing.com/profile/John_Behrens" target="_blank" rel="me"><img src="http://www.xing.com/img/buttons/9_de_btn.gif" width="80" height="15" alt="John Behrens"></a>
</div>    
</div>

<div class="row">
<div class="span 1"></div>
    <div class="span6 well">
        <h2><?php echo $this->translate('Software Development') ?></h2>
        Wir unterstützen ihre Entwicklungsabteilung.
        <p><a class="btn btn-primary" href="<?=$this->url('development')?>"><?php echo $this->translate('Software Development') ?> &raquo;</a></p>
    </div>

</div>

<div class="row">
<div class="span 1"></div>
    <div class="span6 well">
        <h2><?php echo $this->translate('Technical Training') ?></h2>
        Training und Coaching um ihr Team auf den neusten stand zu bringen und Effizienz und Motivation zu steigern.
        <p><a class="btn btn-primary" href="<?=$this->url('training')?>"><?php echo $this->translate('Training') ?> &raquo;</a></p>
   </div>
</div>