
    
    
<div class="span6 well">
    <h1><?php echo sprintf($this->translate('WebConsults.eu'), '<span class="zf-green">', '</span>') ?></h1>
    We are focused on the Development of high quality web Applications.
    Our favorite technologies are PHP, MySQL , Zend Framework 2, NoSQL, SOA, SCRUM, Agile, PHP Unit, Test Driven Development, Netbeans, Linux, NoSQL, JQuery.
    For technical information, tutorials news about those view our 
   <a href="<?=$this->url('blog')?>" target="_blank">Techblog</a> <br />
    <p><a class="btn btn-primary btn-large" href="<?=$this->url('blog')?>"><?php echo $this->translate('Techblog') ?> &raquo;</a></p>
</div>
    
<div class="span3 well">
       <h2><?php echo $this->translate('Contact') ?></h2>
       <p>Our office is Located in Elmshorn near Hamburg</p>       
       <p><a class="btn btn-primary" href="<?=$this->url('contact')?>" ><?php echo $this->translate('Contact') ?> &raquo;</a></p>
       <a href="http://www.xing.com/profile/John_Behrens" target="_blank" rel="me"><img src="http://www.xing.com/img/buttons/9_de_btn.gif" width="80" height="15" alt="John Behrens"></a>
</div>    


<div class="row">
<div class="span 1"></div>
    <div class="span6 well">
        <h2><?php echo $this->translate('Software Development') ?></h2>
        If you need support in your Development department we can support you.
        <p><a class="btn btn-primary" href="<?=$this->url('development')?>"><?php echo $this->translate('Software Development') ?> &raquo;</a></p>
    </div>
</div>

<div class="row">
<div class="span 1"></div>
    <div class="span6 well">
        <h2><?php echo $this->translate('Technical Training') ?></h2>
        Need someone external helping you out with new Stuff ? Think about hiring us as trainer or coach.
        <p><a class="btn btn-primary" href="<?=$this->url('training')?>"><?php echo $this->translate('Training') ?> &raquo;</a></p>
   </div>
</div>